EXPLAIN PLAN FOR
SELECT /*parallel (3)*/ MANAGER_ID, FIRST_NAME, COUNTRY_NAME, COUNTRY_ID, REGION_ID
FROM EMPLOYEES
JOIN DEPARTMENTS USING (MANAGER_ID)
JOIN LOCATIONS USING (LOCATION_ID)
JOIN COUNTRIES USING (COUNTRY_ID)
JOIN REGIONS USING (REGION_ID)

WHERE EMPLOYEE_ID IN
(SELECT EMPLOYEE_ID FROM EMPLOYEES
WHERE REGION_ID = '1' OR REGION_ID = '2' OR REGION_ID = '3' OR REGION_ID = '4' OR COUNTRY_ID= 'DE'
OR COUNTRY_ID = 'AR' OR COUNTRY_ID = 'FR' OR COUNTRY_ID = 'CH' OR COUNTRY_NAME = 'Argentina')
ORDER BY REGION_ID ASC;

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());