EXPLAIN PLAN FOR
SELECT /*parallel (3)*/ COUNTRY_NAME, CITY, REGION_NAME, COUNT(DEPARTMENT_ID)
FROM COUNTRIES 
JOIN LOCATIONS USING (COUNTRY_ID) 
JOIN DEPARTMENTS USING (LOCATION_ID) 
JOIN EMPLOYEES USING (DEPARTMENT_ID)
JOIN REGIONS USING (REGION_ID)
WHERE DEPARTMENT_ID IN 
    (SELECT DEPARTMENT_ID FROM EMPLOYEES 
	 GROUP BY DEPARTMENT_ID 
	 HAVING COUNT(DEPARTMENT_ID)>=0)
GROUP BY COUNTRY_NAME, CITY, REGION_NAME;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());